imports:
    - package-container.yml
    - ../../cache/config/package-container.yml
    - ../../config/config/package-container.yml
    - ../../route/config/package-container.yml
    - ../../container/config/package-container.yml

services:
    controller:
        class: Controller